### ISSUE TITLE
Is it possible to increase the value of maxalleles in gap/src/2ld.c?

### ISSUE THREAD

**Issue by sjmack** [jinghuazhao/R#1]
I am using gap/LDkl() to analyze HLA data, which can have large numbers of alleles at a given locus. 

R aborts when LDkl() is applied to an HLA dataset where one locus has 81 alleles and the second locus has 178 alleles, so that the length of the haplotype vector is 14418. 

I believe this is because `maxalleles` is set to 100 in 2ld.c. If I a haplotype vector of 10000 values, with 100 alleles at each locus, is passed into LDkl(), there is no problem. R aborts with any larger vector.

I am assuming that `maxalleles` is set to 100 because that seems like it would be more than enough for most datasets. 

Is it possible for you to increase the value of `maxalleles` for kbyl() in 2ld.c to >250 in a future release of gap? I'm not sure if setting `maxalleles` to 1000 would have a negative impact on performance, but if it does not, I suspect that that `#define maxalleles 1000` would be more than sufficient to accommodate most HLA datasets. 

This issue came up with a dataset that includes >10000 subjects, and 178 is the largest number of alleles at a locus in that dataset. 

Thank you very much for writing gap!

**Comment by jinghuazhao** [comment]
Thanks -- I will keep a note of this.

________________________________

**Comment by jinghuazhao** [comment]
Done.

**Comment by sjmack** [comment]
Thank you!
